os: osx

osx_image: xcode8.3

env:
  matrix:
    - VERSION=3.8.9 SOURCE=macpython

before_install:
  # - brew update
  - brew install duti
  - sudo duti -s com.apple.TextEdit alfredworkflow all

install:
  - git clone https://github.com/MacPython/terryfy
  - source terryfy/travis_tools.sh
  - get_python_environment $SOURCE $VERSION venv
  - pip install -r requirements-test.txt
  - pip install -r requirements-ci.txt

script:
  - ./run-tests.sh -l
  - ./run-tests.sh

after_success:
  - python-codacy-coverage -r coverage.xml
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
